#include <stdio.h>
#include <conio.h>

int main(void)
{

    
  
	 clrscr();
	
	printf("-------------------------------------\n");
	printf("ãgìcçπï€ó¢	 |        |    \n");
	printf(" HP	Åá/Åá    |        |      \n");
	printf("-------------------------------------\n");
	printf("        ÅQÅ^ÅPÅ_        \n");
	printf("      Å^ (    ∏ Å_		\n");
	printf("     /  Å^ÅPÅPÅ_  ÅR	\n");
	printf("    ò¶ /Å‹    Å‹ÅR  	\n");
	printf("    | / -• /  •- ÇuÅb	\n");
	printf("    |Åb   /      ÅbÅb	\n");
	printf("    |Å»  (._.)   / Åb	\n");
	printf("    | Å»  ÅQÅQ  /  Åb	\n");
	printf("    |  Å»  Å[  /|  Åb	\n");
	printf(" `Å^ÅRÅb Å_ÅQÅ^ ÅR /Å_  \n");
	printf(" Åb  |/Å_ÅQÅQÅQÅ^|/  Åb \n");
	printf(" Åb /             ÅR Åb \n");
	printf(" ÅbÅb  Ç`ÇkÇrÇnÇj  | Åb \n");
	printf("                      \n");
	printf("                      \n");
	printf("                      \n");
	printf("                      \n");
	printf("                      \n");
	printf("                      \n");
	printf(" ------------------------------------\n");
	printf("|ñÏê∂ÇÃãgìcçπï€ó¢Ç™åªÇÍÇΩ!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf(" ------------------------------------\n");
	
    (void)getchar();
	clrscr();

	printf("-------------------------------------\n");
	printf("ãgìcçπï€ó¢	 |        |ÉsÅõÉ`ÉÖÉE    \n");
	printf(" HP	Åá/Åá    |        |HP %d/%d      \n");
	printf("-------------------------------------\n");
	printf("        ÅQÅ^ÅPÅ_        \n");
	printf("      Å^ (    ∏ Å_		\n");
	printf("     /  Å^ÅPÅPÅ_  ÅR	\n");
	printf("    ò¶ /Å‹    Å‹ÅR  	\n");
	printf("    | / -• /  •- ÇuÅb	\n");
	printf("    |Åb   /      ÅbÅb	\n");
	printf("    |Å»  (._.)   / Åb	\n");
	printf("    | Å»  ÅQÅQ  /  Åb	\n");
	printf("    |  Å»  Å[  /|  Åb	\n");
	printf(" `Å^ÅRÅb Å_ÅQÅ^ ÅR /Å_  \n");
	printf(" Åb  |/Å_ÅQÅQÅQÅ^|/  Åb \n");
	printf(" Åb /             ÅR Åb \n");
	printf(" ÅbÅb  Ç`ÇkÇrÇnÇj  | Åb \n");
	printf("                        Å^) Å^) \n");
	printf("                       /  Å‹  ÅR\n");
	printf("                      ÅbÅú_ Åú |/Å_ \n");
	printf("                      (ÅZ Å` ÅZ| Å^\n");
	printf("                      /        |< \n");
	printf("                     Åb     L/ |/ \n");
	printf(" ------------------------------------\n");
	printf("|çsÇØÇ¡!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|ÉsÅõÉ`ÉÖÉE!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf(" ------------------------------------\n");
	
    (void)getchar();
	clrscr();
	
	printf("-------------------------------------\n");
	printf("ãgìcçπï€ó¢	 |        |ÉsÅõÉ`ÉÖÉE    \n");
	printf(" HP	Åá/Åá    |        |HP %d/%d      \n");
	printf("-------------------------------------\n");
	printf("        ÅQÅ^ÅPÅ_        \n");
	printf("      Å^ (    ∏ Å_		\n");
	printf("     /  Å^ÅPÅPÅ_  ÅR	\n");
	printf("    ò¶ /Å‹    Å‹ÅR  	\n");
	printf("    | / -• /  •- ÇuÅb	\n");
	printf("    |Åb   /      ÅbÅb	\n");
	printf("    |Å»  (._.)   / Åb	\n");
	printf("    | Å»  ÅQÅQ  /  Åb	\n");
	printf("    |  Å»  Å[  /|  Åb	\n");
	printf(" `Å^ÅRÅb Å_ÅQÅ^ ÅR /Å_  \n");
	printf(" Åb  |/Å_ÅQÅQÅQÅ^|/  Åb \n");
	printf(" Åb /             ÅR Åb \n");
	printf(" ÅbÅb  Ç`ÇkÇrÇnÇj  | Åb \n");
	printf("                        Å^) Å^) \n");
	printf("                       /  Å‹  ÅR\n");
	printf("                      ÅbÅú_ Åú |/Å_ \n");
	printf("                      (ÅZ Å` ÅZ| Å^\n");
	printf("                      /        |< \n");
	printf("                     Åb     L/ |/ \n");
	printf(" ------------------------------------\n");
	printf("| *Ç≈ÇÒÇ±Ç§ÇπÇ¡Ç©|ñΩíÜ:100à–óÕ:10 |\n");
	printf("| *Ç≈ÇÒÇ´ÉVÉáÉbÉN|ñΩíÜ:50 à–óÕ:30 |\n");
	printf("| *ÉLÉYÇÆÇ∑ÇË    |ñΩíÜ:100HP20âÒïú|\n");
	printf("| *Ç©Ç›Ç»ÇË      |ñΩíÜ:30 à–óÕ:40 |\n");
	printf(" ------------------------------------\n");
	
    (void)getchar();
	clrscr();
	
	printf("-------------------------------------\n");
	printf("ãgìcçπï€ó¢	 |        |ÉsÅõÉ`ÉÖÉE    \n");
	printf(" HP	Åá/Åá    |        |HP %d/%d      \n");
	printf("-------------------------------------\n");
	printf("        ÅQÅ^ÅPÅ_        \n");
	printf("      Å^ (    ∏ Å_		\n");
	printf("     /  Å^ÅPÅPÅ_  ÅR	\n");
	printf("    ò¶ /Å‹    Å‹ÅR  	\n");
	printf("    | / -• /  •- ÇuÅb	\n");
	printf("    |Åb   /      ÅbÅb	\n");
	printf("    |Å»  (._.)   / Åb	\n");
	printf("    | Å»  ÅQÅQ  /  Åb	\n");
	printf("    |  Å»  Å[  /|  Åb	\n");
	printf(" `Å^ÅRÅb Å_ÅQÅ^ ÅR /Å_  \n");
	printf(" Åb  |/Å_ÅQÅQÅQÅ^|/  Åb \n");
	printf(" Åb /             ÅR Åb \n");
	printf(" ÅbÅb  Ç`ÇkÇrÇnÇj  | Åb \n");
	printf("                        Å^) Å^) \n");
	printf("                       /  Å‹  ÅR\n");
	printf("                      ÅbÅú_ Åú |/Å_ \n");
	printf("                      (ÅZ Å` ÅZ| Å^\n");
	printf("                      /        |< \n");
	printf("                     Åb     L/ |/ \n");
	printf(" ------------------------------------\n");
	printf("|ÉsÅõÉ`ÉÖÉEÇÃ%c!                   \n");
	printf("|ãgìcçπï€ó¢Ç…ÇÕå¯Ç©Ç»Ç©Ç¡ÇΩ!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf(" ------------------------------------\n");
	
    (void)getchar();
	clrscr();
	
	printf("-------------------------------------\n");
	printf("ãgìcçπï€ó¢	 |        |ÉsÅõÉ`ÉÖÉE    \n");
	printf(" HP	Åá/Åá    |        |HP %d/%d      \n");
	printf("-------------------------------------\n");
	printf("        ÅQÅ^ÅPÅ_        \n");
	printf("      Å^ (    ∏ Å_		\n");
	printf("     /  Å^ÅPÅPÅ_  ÅR	\n");
	printf("    ò¶ /Å‹    Å‹ÅR  	\n");
	printf("    | / Åõ•/ •ÅZ ÇuÅb	\n");
	printf("    |Åb   /      ÅbÅb	\n");
	printf("    |Å»  (._.)   / Åb	\n");
	printf("    | Å»  ÅQÅQ  /  Åb	\n");
	printf("    |  Å»  Å[  /|  Åb	\n");
	printf(" `Å^ÅRÅb Å_ÅQÅ^ ÅR /Å_  \n");
	printf(" Åb  |/Å_ÅQÅQÅQÅ^|/  Åb \n");
	printf(" Åb /             ÅR Åb \n");
	printf(" ÅbÅb  Ç`ÇkÇrÇnÇj  | Åb \n");
	printf("                        Å^) Å^) \n");
	printf("                       /  Å‹  ÅR\n");
	printf("                      ÅbÅú_ Åú |/Å_ \n");
	printf("                      (ÅZ Å` ÅZ| Å^\n");
	printf("                      /        |< \n");
	printf("                     Åb     L/ |/ \n");
	printf(" ------------------------------------\n");
	printf("|ãgìcçπï€ó¢Ç™ãNÇ´ÇΩ!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf(" ------------------------------------\n");
	
    (void)getchar();
	clrscr();
	
	printf("-------------------------------------\n");
	printf("ãgìcçπï€ó¢	 |        |ÉsÅõÉ`ÉÖÉE    \n");
	printf(" HP	Åá/Åá    |        |HP %d/%d      \n");
	printf("-------------------------------------\n");
	printf("        ÅQÅ^ÅPÅ_        \n");
	printf("      Å^ (    ∏ Å_		\n");
	printf("     /  Å^ÅPÅPÅ_  ÅR	\n");
	printf("    ò¶ /Å‹    Å‹ÅR  	\n");
	printf("    | / Åõ•/ •ÅZ ÇuÅb	\n");
	printf("    |Åb   /      ÅbÅb	\n");
	printf("    |Å»  (._.)   / Åb	\n");
	printf("    | Å»  ÅQÅQ  /  Åb	\n");
	printf("    |  Å»  Å[  /|  Åb	\n");
	printf(" `Å^ÅRÅb Å_ÅQÅ^ ÅR /Å_  \n");
	printf(" Åb  |/Å_ÅQÅQÅQÅ^|/  Åb \n");
	printf(" Åb /             ÅR Åb \n");
	printf(" ÅbÅb  Ç`ÇkÇrÇnÇj  | Åb \n");
	printf("                        Å^) Å^) \n");
	printf("                       /  Å‹  ÅR\n");
	printf("                      ÅbÅú_ Åú |/Å_ \n");
	printf("                      (ÅZ Å` ÅZ| Å^\n");
	printf("                      /        |< \n");
	printf("                     Åb     L/ |/ \n");
	printf(" ------------------------------------\n");
	printf("|ãgìcçπï€ó¢ÇÕñ∞Ç¡ÇƒÇ¢ÇΩÇÊÇ§Çæ!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf(" ------------------------------------\n");
	
    (void)getchar();
	clrscr();
	
	printf("-------------------------------------\n");
	printf("ãgìcçπï€ó¢	 |        |ÉsÅõÉ`ÉÖÉE    \n");
	printf(" HP	Åá/Åá    |        |HP %d/%d      \n");
	printf("-------------------------------------\n");
	printf("        ÅQÅ^ÅPÅ_        \n");
	printf("      Å^ (    ∏ Å_		\n");
	printf("     /  Å^ÅPÅPÅ_  ÅR	\n");
	printf("    ò¶ /Å‹    Å‹ÅR  	\n");
	printf("    | / Å[•/ •Å[ ÇuÅb	\n");
	printf("    |Åb   /      ÅbÅb	\n");
	printf("    |Å»  (._.)   / Åb	\n");
	printf("    | Å»        /  Åb	\n");
	printf("    |  Å» (Å[) /|  Åb	\n");
	printf(" `Å^ÅRÅb Å_ÅQÅ^ ÅR /Å_  \n");
	printf(" Åb  |/Å_ÅQÅQÅQÅ^|/  Åb \n");
	printf(" Åb /             ÅR Åb \n");
	printf(" ÅbÅb  Ç`ÇkÇrÇnÇj  | Åb \n");
	printf("                        Å^) Å^) \n");
	printf("                       /  Å‹  ÅR\n");
	printf("                      ÅbÅú_ Åú |/Å_ \n");
	printf("                      (ÅZ Å` ÅZ| Å^\n");
	printf("                      /        |< \n");
	printf("                     Åb     L/ |/ \n");
	printf(" ------------------------------------\n");
	printf("|ãgìcçπï€ó¢ÇÃÇ†Ç≠Ç—!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf(" ------------------------------------\n");
	
    (void)getchar();
	clrscr();
	
    printf("-------------------------------------\n");
	printf("ãgìcçπï€ó¢	 |           \n");
	printf(" HP	Åá/Åá    |              \n");
	printf("-------------------------------------\n");
	printf("        ÅQÅ^ÅPÅ_        \n");
	printf("      Å^ (    ∏ Å_		\n");
	printf("     /  Å^ÅPÅPÅ_  ÅR	\n");
	printf("    ò¶ /Å‹    Å‹ÅR  	\n");
	printf("    | / ÅZ•/ •ÅZ ÇuÅb	\n");
	printf("    |Åb   /      ÅbÅb	\n");
	printf("    |Å»  (._.)   / Åb	\n");
	printf("    | Å»  ÅQÅQ  /  Åb	\n");
	printf("    |  Å»  Å[  /|  Åb	\n");
	printf(" `Å^ÅRÅb Å_ÅQÅ^ ÅR /Å_  \n");
	printf(" Åb  |/Å_ÅQÅQÅQÅ^|/  Åb \n");
	printf(" Åb /             ÅR Åb \n");
	printf(" ÅbÅb  Ç`ÇkÇrÇnÇj  | Åb \n");
	printf("                        \n");
	printf("                       \n");
	printf("                      \n");
	printf("                     \n");
	printf("                       \n");
	printf("                     \n");
	printf(" ------------------------------------\n");
	printf("|Ç±ÇÃê¢äEÇÕè¡Ç¶ÇƒÇµÇ‹Ç¡ÇΩ!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf("|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|\n");
	printf(" ------------------------------------\n");
	
    (void)getchar();
	clrscr();
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");	
	printf("\n");
	printf("\n");
	printf("\n");
	printf("ÉQÅ`ÉÄÉIÅ`ÉoÅ`\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	
    return (0);
}
